name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install-dep
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev g++
      
    - name: make
      run: cd ./src/ && make

    - name: run
      run: ./main
